abstract class ContinueSetupState{}
class ContinueSetupIntialState extends ContinueSetupState{}
class ContinueSetupSelectedGenderState extends ContinueSetupState{}
class ContinueSetupSelectedGenderSuccessState extends ContinueSetupState{}
class ContinueSetupSelectedGenderFailState extends ContinueSetupState{}
